spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: root
    password: root
#    hikari:
#      schema: public
#      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
#      connection-timeout: 10000
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true
#    default-schema: public
#    out-of-order: false

logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            INFO
          JpaTransactionManager:
            DEBUG
        transaction:
          INFO
        interceptor:
          TRACE
