--V1__initial_setup.sql

-- CREATE TABLE flyway_schema_history
-- (
--     installed_rank INTEGER                                   NOT NULL,
--     version        VARCHAR(50),
--     description    VARCHAR(200)                              NOT NULL,
--     type           VARCHAR(20)                               NOT NULL,
--     script         VARCHAR(1000)                             NOT NULL,
--     checksum       INTEGER,
--     installed_by   VARCHAR(100)                              NOT NULL,
--     installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
--     execution_time INTEGER                                   NOT NULL,
--     success        BOOLEAN                                   NOT NULL,
--     CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
-- );

--CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE users_credentials
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    birth_date   date                                    NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    patronym     VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    user_id      BIGINT,
    CONSTRAINT users_credentials_pkey PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT       NOT NULL,
    roles   VARCHAR(255) NOT NULL
);

ALTER TABLE users
    ADD CONSTRAINT uk_r43af9ap4edm43mmtq01oddj6 UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT uk_r53o2ojjw4fikudfnsuuga336 UNIQUE (password);

ALTER TABLE users_credentials
    ADD CONSTRAINT uk_a8feqewf49113lb87l8hsxux UNIQUE (phone_number);

ALTER TABLE users_credentials
    ADD CONSTRAINT uk_b60r7mjr4cj6xbnyeyrpic8li UNIQUE (user_id);

ALTER TABLE users_credentials
    ADD CONSTRAINT uk_mhu78g9jl2bxvoc0p97odub2f UNIQUE (email);

ALTER TABLE users_credentials
    ADD CONSTRAINT fk9lp2rjt4dd62lm7agk0l9sbag FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;